gateway:
  image: demo/kaazing-jms-gateway-4.0.7
  ports:
   - "8000:8000"
   - "8001:8001"
  links:
   - activemq
  environment:
   - DNSDOCK_NAME=gateway
   - DNSDOCK_IMAGE=demo

activemq:
  image: demo/activemq-5.10.0
  ports:
   - 8161
  environment:
   - DNSDOCK_NAME=activemq
   - DNSDOCK_IMAGE=demo
